### PR TITLE
Update gpt4v_model.py

### PR DESCRIPTION
**Pull request by daaniyaan**
allowing user to give api key directly from GPT4V class in addition to env variable.

### CODE REVIEW

**Comment by daaniyaan** [comment]
This will probably help and will be the solution for this problem:
CleanShot 2023-11-09 at 00 30 58@2x

**Comment by daaniyaan** [comment]
.

**Comment by capjamesg** [comment]
Thank you for your PR! We now allow you to pass in your API key through the `api_key` parameter in model instantiation. Thus, we are closing this PR. Thanks again!

**Comment by Buckler89** [comment]
Hi @capjamesg! 
Sorry but i don't see any changes in the main branch yet. When this PR will be merged?

**Comment by capjamesg** [comment]
The changes are now visible here: https://github.com/autodistill/autodistill-gpt-4v/blob/main/autodistill_gpt_4v/gpt4v_model.py#L16

Run `pip install --upgrade autodistill-gpt-4v` to download the latest version.

**Pull request closed without merging**
